server:
  requestLog:
    appenders:
      - type: console
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8088

logging:
  level: INFO
  appenders:
    - type: console